version: '3.8'

services:
  db:
    image: mysql:8.0.27
    volumes:  
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - db

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
       - ./wp-admin:/var/www/html/wp-admin 
    ports:
      - 8000:80
    restart: always
    env_file:
      - .env

volumes:
  db_data:
  wordpress_data:
